version: "3.9"
services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: batch
      POSTGRES_PASSWORD: batch
      POSTGRES_DB: batch_db
    volumes:
      - ./db/postgresql/data:/var/lib/postgresql/data
      - ./db/postgresql/init.d:/docker-entrypoint-initdb.d
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: inventory
      MYSQL_PASSWORD: inventory
      MYSQL_DATABASE: inventory_db
    volumes:
      - ./db/mysql/conf.d:/etc/mysql/conf.d
      - ./db/mysql/init.d:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  oracle:
    container_name: oracle
    image: wnameless/oracle-xe-11g-r2:latest
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_ALLOW_REMOTE: true
      ORACLE_DISABLE_ASYNCH_IO: true
      TZ: Asia/Seoul
    volumes:
      - ./db/oracle/oradata:/etc/oracle/oradata
      - ./db/oracle/init.d:/docker-entrypoint-initdb.d
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "9090:9090"                  # Jenkins Web UI 포트
      - "50000:50000"                # Jenkins API 포트
    user: jenkins
    environment:
      JENKINS_OPTS: --httpPort=9090  # 기본포트가 8080이나 9090으로 변경
    volumes:
      - ./jenkins_home:/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock